---
- hosts: videoservers
  remote_user: "peko"

  tasks:
  - name: Set up a systemd service for videoserver instances
    vars:
      - cam_serial: "{{item.serial}}"
      - cam_name: "{{item.name}}"
    template:
      src: videostream.service.j2
      dest: /lib/systemd/system/videostream-{{item.name}}.service
      owner: root
      group: root
      mode: '0644'
    become: true
    with_items: "{{ cam_config }}"

  - name: Set up a systemd service for managing all videoserver instances simultaneously
    template:
      src: videostreams.service.j2
      dest: /lib/systemd/system/videostreams.service
      owner: root
      group: root
      mode: '0644'
    become: true

    #  - name: Enable and start services
    #    service:
    #      name: {{ item }}.service
    #      state: started
    #      enabled: yes
    #    become: true
    #    with_item:
    #      - videoserverinstance@1
    #      - videoserverinstance@2
    #      - videoserverinstance@3
    #      - videoserverinstance@4
    #      - videoserver
    
  - name: Create a streaming script into the home directory
    template:
      src: video_streamer.sh.j2
      dest: /home/peko/video_streamer.sh
      owner: "peko"
      group: "peko"
      mode: '0744'

  - name: Prepare a folder for rtsp-simple-server
    file:
      path: "/home/peko/rtsp-simple-server"
      state: directory
      owner: "peko"
      group: "peko"
      mode: '0775'

  - name: Downloading and unpacking rtsp-simple-server
    unarchive:
      src: https://github.com/aler9/rtsp-simple-server/releases/download/v0.16.0/rtsp-simple-server_v0.16.0_linux_amd64.tar.gz
      remote_src: yes
      dest: /home/peko/rtsp-simple-server

  - name: Set up a service for rtsp-server
    template:
      src: rtsp-server.service.j2
      dest: /lib/systemd/system/rtsp-server.service
      owner: root
      group: root
      mode: '0644'
    become: true

  - name: Enable rtsp server service
    service:
      name: "rtsp-server"
      enabled: yes
      state: restarted
    become: true

  - name: Enable videostream services
    service:
      name: "videostream-{{ item.name }}"
      enabled: yes
      state: restarted
    with_items: "{{ cam_config }}"
    become: true

  - name: Enable and start videostreams service
    service:
      name: "videostreams"
      state: restarted
      enabled: yes
    become: true
